version: "3.8"
services:
  app:
    container_name: app
    build: .
    environment:
      - MONGO_URI=mongo-db
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
